spring.application.name=ChatApplication
spring.datasource.url=jdbc:postgresql://cf980tnnkgv1bp.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d6mtp5vkatt581
spring.datasource.username=u4ukjc7ac3j0fd
spring.datasource.password=p2f1cb8094e2acebdb2d6cb710a58f25318d996c9037f1694516dd615d25ed246
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
